-- Suhail Medical Dictionary v21.21
-- Fair-use real AI quota + verified owner/admin controls.
-- This file contains no provider secret. Store provider secrets only in Supabase Edge Function secrets.

create table if not exists public.ai_quota_config (
  id smallint primary key default 1 check (id = 1),
  enabled boolean not null default true,
  provider text not null default 'groq',
  model text not null default 'openai/gpt-oss-20b',
  daily_global_tokens bigint not null default 200000 check (daily_global_tokens > 0),
  daily_global_requests integer not null default 900 check (daily_global_requests > 0),
  daily_user_tokens integer not null default 2000 check (daily_user_tokens > 0),
  daily_user_requests integer not null default 10 check (daily_user_requests > 0),
  max_output_tokens integer not null default 350 check (max_output_tokens between 64 and 2000),
  updated_at timestamptz not null default now()
);

insert into public.ai_quota_config (id)
values (1)
on conflict (id) do nothing;

create table if not exists public.ai_usage_daily (
  day date not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  requests integer not null default 0,
  tokens_reserved bigint not null default 0,
  last_request_at timestamptz,
  primary key (day, user_id)
);

create table if not exists public.ai_global_usage_daily (
  day date primary key,
  requests integer not null default 0,
  tokens_reserved bigint not null default 0,
  last_request_at timestamptz
);

create table if not exists public.ai_request_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid references auth.users(id) on delete set null,
  status text not null,
  reserved_tokens integer not null default 0,
  provider_status integer,
  latency_ms integer
);

alter table public.ai_quota_config enable row level security;
alter table public.ai_usage_daily enable row level security;
alter table public.ai_global_usage_daily enable row level security;
alter table public.ai_request_events enable row level security;

revoke all on public.ai_quota_config from anon, authenticated;
revoke all on public.ai_usage_daily from anon, authenticated;
revoke all on public.ai_global_usage_daily from anon, authenticated;
revoke all on public.ai_request_events from anon, authenticated;

create or replace function public.smd_ai_reserve(
  p_user_id uuid,
  p_estimated_tokens integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  cfg public.ai_quota_config%rowtype;
  d date := (now() at time zone 'utc')::date;
  reset_at timestamptz := ((d + 1)::timestamp at time zone 'utc');
  u public.ai_usage_daily%rowtype;
  g public.ai_global_usage_daily%rowtype;
  estimate integer := greatest(1, least(coalesce(p_estimated_tokens, 1), 6000));
begin
  select * into cfg
  from public.ai_quota_config
  where id = 1
  for update;

  if not found or not cfg.enabled then
    return jsonb_build_object(
      'allowed', false,
      'code', 'AI_DISABLED',
      'message', 'AI is temporarily unavailable.',
      'reset_at', reset_at
    );
  end if;

  insert into public.ai_global_usage_daily(day)
  values (d)
  on conflict (day) do nothing;

  insert into public.ai_usage_daily(day, user_id)
  values (d, p_user_id)
  on conflict (day, user_id) do nothing;

  select * into g
  from public.ai_global_usage_daily
  where day = d
  for update;

  select * into u
  from public.ai_usage_daily
  where day = d and user_id = p_user_id
  for update;

  if g.requests >= cfg.daily_global_requests
     or g.tokens_reserved + estimate > cfg.daily_global_tokens then
    return jsonb_build_object(
      'allowed', false,
      'code', 'GLOBAL_DAILY_LIMIT',
      'message', 'Today''s shared free AI limit has been reached.',
      'reset_at', reset_at,
      'remaining_global_tokens', greatest(0, cfg.daily_global_tokens - g.tokens_reserved),
      'remaining_user_tokens', greatest(0, cfg.daily_user_tokens - u.tokens_reserved)
    );
  end if;

  if u.requests >= cfg.daily_user_requests
     or u.tokens_reserved + estimate > cfg.daily_user_tokens then
    return jsonb_build_object(
      'allowed', false,
      'code', 'USER_DAILY_LIMIT',
      'message', 'Your free AI limit for today has been reached.',
      'reset_at', reset_at,
      'remaining_global_tokens', greatest(0, cfg.daily_global_tokens - g.tokens_reserved),
      'remaining_user_tokens', greatest(0, cfg.daily_user_tokens - u.tokens_reserved)
    );
  end if;

  update public.ai_global_usage_daily
  set requests = requests + 1,
      tokens_reserved = tokens_reserved + estimate,
      last_request_at = now()
  where day = d;

  update public.ai_usage_daily
  set requests = requests + 1,
      tokens_reserved = tokens_reserved + estimate,
      last_request_at = now()
  where day = d and user_id = p_user_id;

  return jsonb_build_object(
    'allowed', true,
    'code', 'OK',
    'reset_at', reset_at,
    'reserved_tokens', estimate,
    'remaining_global_tokens', greatest(0, cfg.daily_global_tokens - (g.tokens_reserved + estimate)),
    'remaining_user_tokens', greatest(0, cfg.daily_user_tokens - (u.tokens_reserved + estimate)),
    'remaining_user_requests', greatest(0, cfg.daily_user_requests - (u.requests + 1)),
    'model', cfg.model,
    'max_output_tokens', cfg.max_output_tokens
  );
end;
$$;

revoke all on function public.smd_ai_reserve(uuid, integer) from public, anon, authenticated;
grant execute on function public.smd_ai_reserve(uuid, integer) to service_role;

create or replace function public.smd_ai_admin_metrics()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  role_name text := coalesce(auth.jwt()->'app_metadata'->>'smd_role', '');
  d date := (now() at time zone 'utc')::date;
  cfg public.ai_quota_config%rowtype;
  g public.ai_global_usage_daily%rowtype;
begin
  if role_name not in ('owner','admin') then
    raise exception 'Not authorized';
  end if;

  select * into cfg from public.ai_quota_config where id = 1;
  select * into g from public.ai_global_usage_daily where day = d;

  return jsonb_build_object(
    'date', d,
    'enabled', cfg.enabled,
    'provider', cfg.provider,
    'model', cfg.model,
    'global', jsonb_build_object(
      'requests', coalesce(g.requests, 0),
      'tokens_reserved', coalesce(g.tokens_reserved, 0),
      'request_limit', cfg.daily_global_requests,
      'token_limit', cfg.daily_global_tokens
    ),
    'per_user', jsonb_build_object(
      'request_limit', cfg.daily_user_requests,
      'token_limit', cfg.daily_user_tokens
    ),
    'active_users_today', (
      select count(*) from public.ai_usage_daily where day = d and requests > 0
    ),
    'reset_at', ((d + 1)::timestamp at time zone 'utc')
  );
end;
$$;

revoke all on function public.smd_ai_admin_metrics() from public, anon;
grant execute on function public.smd_ai_admin_metrics() to authenticated;

create or replace function public.smd_ai_admin_update_config(
  p_enabled boolean,
  p_daily_global_tokens bigint,
  p_daily_global_requests integer,
  p_daily_user_tokens integer,
  p_daily_user_requests integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  role_name text := coalesce(auth.jwt()->'app_metadata'->>'smd_role', '');
begin
  if role_name not in ('owner','admin') then
    raise exception 'Not authorized';
  end if;

  update public.ai_quota_config
  set enabled = coalesce(p_enabled, enabled),
      daily_global_tokens = greatest(1000, least(coalesce(p_daily_global_tokens, daily_global_tokens), 2000000)),
      daily_global_requests = greatest(1, least(coalesce(p_daily_global_requests, daily_global_requests), 10000)),
      daily_user_tokens = greatest(250, least(coalesce(p_daily_user_tokens, daily_user_tokens), 100000)),
      daily_user_requests = greatest(1, least(coalesce(p_daily_user_requests, daily_user_requests), 500)),
      updated_at = now()
  where id = 1;

  return public.smd_ai_admin_metrics();
end;
$$;

revoke all on function public.smd_ai_admin_update_config(boolean, bigint, integer, integer, integer) from public, anon;
grant execute on function public.smd_ai_admin_update_config(boolean, bigint, integer, integer, integer) to authenticated;
