-- Suhail Medical Dictionary - Supabase production schema
-- Run once in Supabase SQL Editor. Then create your account and run:
-- UPDATE public.profiles SET is_owner=true WHERE email='YOUR_OWNER_EMAIL';

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  display_name text,
  is_owner boolean not null default false,
  allow_owner_review boolean not null default false,
  privacy_ack_at timestamptz,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz
);
create table if not exists public.chats (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null default 'New medical chat' check (char_length(title)<=120),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.ai_messages (
  id uuid primary key default gen_random_uuid(),
  chat_id uuid not null references public.chats(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null check (role in ('user','assistant','system')),
  content text not null check (char_length(content)<=30000),
  selected_terms jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  edited_at timestamptz
);
create table if not exists public.user_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  event_type text not null check (char_length(event_type)<=80),
  metadata jsonb not null default '{}'::jsonb,
  user_agent text,
  created_at timestamptz not null default now()
);
create table if not exists public.term_translation_cache (
  term_id text not null,
  language text not null,
  definition text not null,
  explanation text,
  model text,
  reviewed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key(term_id,language)
);
create table if not exists public.ai_usage_daily (
  user_id uuid not null references public.profiles(id) on delete cascade,
  usage_day date not null default current_date,
  chat_count integer not null default 0,
  translation_count integer not null default 0,
  primary key(user_id,usage_day)
);

create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path=public as $$
declare v_review boolean := false; v_privacy boolean := false;
begin
  begin v_review := coalesce((new.raw_user_meta_data->>'allow_owner_review')::boolean,false); exception when others then v_review:=false; end;
  begin v_privacy := coalesce((new.raw_user_meta_data->>'privacy_accepted')::boolean,false); exception when others then v_privacy:=false; end;
  insert into public.profiles(id,email,allow_owner_review,privacy_ack_at,created_at)
  values(new.id,coalesce(new.email,''),v_review,case when v_privacy then now() else null end,now())
  on conflict(id) do update set email=excluded.email;
  return new;
end;$$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.chats enable row level security;
alter table public.ai_messages enable row level security;
alter table public.user_events enable row level security;
alter table public.term_translation_cache enable row level security;
alter table public.ai_usage_daily enable row level security;

create or replace function public.is_owner() returns boolean
language sql stable security definer set search_path=public as $$
 select exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_owner=true)
$$;

-- Ordinary user data access: strictly self-only.
drop policy if exists "profile self read" on public.profiles;
create policy "profile self read" on public.profiles for select using (id=auth.uid());
drop policy if exists "chats own read" on public.chats;
create policy "chats own read" on public.chats for select using (user_id=auth.uid());
drop policy if exists "chats own insert" on public.chats;
create policy "chats own insert" on public.chats for insert with check (user_id=auth.uid());
drop policy if exists "chats own update" on public.chats;
create policy "chats own update" on public.chats for update using (user_id=auth.uid()) with check (user_id=auth.uid());
drop policy if exists "chats own delete" on public.chats;
create policy "chats own delete" on public.chats for delete using (user_id=auth.uid());
drop policy if exists "messages own read" on public.ai_messages;
create policy "messages own read" on public.ai_messages for select using (user_id=auth.uid());
drop policy if exists "messages edit own prompt" on public.ai_messages;
create policy "messages edit own prompt" on public.ai_messages for update using (user_id=auth.uid() and role='user' and exists(select 1 from public.chats c where c.id=chat_id and c.user_id=auth.uid())) with check (user_id=auth.uid() and role='user' and exists(select 1 from public.chats c where c.id=chat_id and c.user_id=auth.uid()));
drop policy if exists "events own insert" on public.user_events;
create policy "events own insert" on public.user_events for insert with check (user_id=auth.uid());
drop policy if exists "translation public read" on public.term_translation_cache;
create policy "translation public read" on public.term_translation_cache for select using (true);

create or replace function public.touch_last_seen() returns void
language sql security definer set search_path=public as $$
 update public.profiles set last_seen_at=now() where id=auth.uid()
$$;
create or replace function public.set_owner_review_consent(p_allow boolean) returns void
language plpgsql security definer set search_path=public as $$
begin
 if auth.uid() is null then raise exception 'Authentication required'; end if;
 update public.profiles set allow_owner_review=coalesce(p_allow,false),privacy_ack_at=coalesce(privacy_ack_at,now()) where id=auth.uid();
end;$$;

-- Owner analytics functions. Content audit requires the user's current opt-in.
create or replace function public.admin_dashboard_stats()
returns table(total_users bigint,total_chats bigint,total_messages bigint,total_events bigint)
language plpgsql security definer set search_path=public as $$
begin
 if not public.is_owner() then raise exception 'Owner access required'; end if;
 return query select (select count(*) from public.profiles),(select count(*) from public.chats),(select count(*) from public.ai_messages),(select count(*) from public.user_events);
end;$$;

create or replace function public.admin_user_summaries()
returns table(id uuid,email text,created_at timestamptz,last_seen_at timestamptz,is_owner boolean,allow_owner_review boolean,chat_count bigint,message_count bigint)
language plpgsql security definer set search_path=public as $$
begin
 if not public.is_owner() then raise exception 'Owner access required'; end if;
 return query select p.id,p.email,p.created_at,p.last_seen_at,p.is_owner,p.allow_owner_review,
  (select count(*) from public.chats c where c.user_id=p.id),
  (select count(*) from public.ai_messages m where m.user_id=p.id)
 from public.profiles p order by p.created_at desc;
end;$$;

create or replace function public.admin_recent_events(p_limit integer default 100)
returns table(id bigint,user_id uuid,event_type text,metadata jsonb,user_agent text,created_at timestamptz)
language plpgsql security definer set search_path=public as $$
begin
 if not public.is_owner() then raise exception 'Owner access required'; end if;
 return query select e.id,e.user_id,e.event_type,e.metadata,e.user_agent,e.created_at from public.user_events e order by e.created_at desc limit least(greatest(coalesce(p_limit,100),1),500);
end;$$;

create or replace function public.admin_user_chats(p_user uuid)
returns table(id uuid,title text,created_at timestamptz,updated_at timestamptz)
language plpgsql security definer set search_path=public as $$
begin
 if not public.is_owner() then raise exception 'Owner access required'; end if;
 if not exists(select 1 from public.profiles p where p.id=p_user and p.allow_owner_review=true) then return; end if;
 return query select c.id,c.title,c.created_at,c.updated_at from public.chats c where c.user_id=p_user order by c.updated_at desc;
end;$$;

create or replace function public.admin_chat_messages(p_chat uuid)
returns table(id uuid,role text,content text,selected_terms jsonb,created_at timestamptz,edited_at timestamptz)
language plpgsql security definer set search_path=public as $$
begin
 if not public.is_owner() then raise exception 'Owner access required'; end if;
 if not exists(select 1 from public.chats c join public.profiles p on p.id=c.user_id where c.id=p_chat and p.allow_owner_review=true) then return; end if;
 return query select m.id,m.role,m.content,m.selected_terms,m.created_at,m.edited_at from public.ai_messages m where m.chat_id=p_chat order by m.created_at;
end;$$;

create or replace function public.consume_ai_quota(p_user uuid,p_kind text,p_limit integer)
returns boolean language plpgsql security definer set search_path=public as $$
declare allowed boolean := false;
begin
 if p_user is null or p_limit < 1 or p_kind not in ('chat','translation') then return false; end if;
 insert into public.ai_usage_daily(user_id,usage_day) values(p_user,current_date) on conflict do nothing;
 if p_kind='chat' then
   update public.ai_usage_daily set chat_count=chat_count+1 where user_id=p_user and usage_day=current_date and chat_count < p_limit returning true into allowed;
 else
   update public.ai_usage_daily set translation_count=translation_count+1 where user_id=p_user and usage_day=current_date and translation_count < p_limit returning true into allowed;
 end if;
 return coalesce(allowed,false);
end;$$;

revoke all on function public.admin_dashboard_stats() from public;
revoke all on function public.admin_user_summaries() from public;
revoke all on function public.admin_recent_events(integer) from public;
revoke all on function public.admin_user_chats(uuid) from public;
revoke all on function public.admin_chat_messages(uuid) from public;
revoke all on function public.consume_ai_quota(uuid,text,integer) from public;
grant execute on function public.admin_dashboard_stats() to authenticated;
grant execute on function public.admin_user_summaries() to authenticated;
grant execute on function public.admin_recent_events(integer) to authenticated;
grant execute on function public.admin_user_chats(uuid) to authenticated;
grant execute on function public.admin_chat_messages(uuid) to authenticated;
grant execute on function public.consume_ai_quota(uuid,text,integer) to service_role;
grant execute on function public.touch_last_seen() to authenticated;
grant execute on function public.set_owner_review_consent(boolean) to authenticated;

grant select on public.profiles,public.chats,public.ai_messages to authenticated;
grant insert,update,delete on public.chats to authenticated;
grant update on public.ai_messages to authenticated;
grant insert on public.user_events to authenticated;
grant select on public.term_translation_cache to anon,authenticated;

create index if not exists chats_user_idx on public.chats(user_id,updated_at desc);
create index if not exists messages_chat_idx on public.ai_messages(chat_id,created_at);
create index if not exists messages_user_idx on public.ai_messages(user_id,created_at desc);
create index if not exists events_user_idx on public.user_events(user_id,created_at desc);
